### ISSUE TITLE
WICS_Stage1

### ISSUE THREAD

**Issue by minhtumn** [bitprj/onboarding#12]
# Stage 1: Preparation
## Step 1: Workshop Proposal
- [x] Choose Topic
- [x] Key Components Listed
- [x] Tentative Dates of Stages with Set Completion Date
- [ ] Place into designated page in GitBooks
- [ ] Review with Dev

## Step 2: Interactive Component Idea
- [ ] Summary of General Idea
- [ ] Step by Step of How
- [ ] Review with Dev

## Step 3: Responsibilities Delegated
- [ ] Timeline of Responsibilities with Specified Delegations
- [ ] Review with Dev
