### ISSUE TITLE
Shannon Leone

### ISSUE THREAD

**Issue by minhtumn** [bitprj/onboarding#83]
# Marketing Onboarding Checklist

### Week 0:
**EduFlow**
- [x] Get started on edu flow course and complete it in 7 days 
*Link to eduflow: [Marketing Eduflow](https://app.eduflow.com/join/W4CAEZ)

**Greeting:**  
- [x] Send a greeting message through the #welcome Channel 
    - Name 
    - Position
    - Major 
    - Year
    - Spirit Animal

**Tasks:** 
- [x] Document a system for team members in Bit Project to add their blogposts to the content pipeline.
- [x] Create a system that keeps track of the status of each blogpost and how social media promotions can be scheduled. 

**Meetings:** 
- [x] Meet with Writing Team @ Victoria Xu (@vkxu657)

- [x] Meet with Developer Relations Team @ Shreya (@shreyagupta98)
 
- [x] Meet with Graphic Design Team @ Rochelle (@rochelledai)

- [x] Meet with Engineering Team @ Bryan W (@wongband)

- [x] Meeting with People Team @ Becca (@beccatran)

**Welcome Webinar**
- [x] Complete live [Welcome Webinar](https://zoom.us/j/4639175564)
  - Note that this will be hosted by Daniel Kim, the president of Bit Project, every Monday at 11 am Pacific Standard Time. Please move on to the next steps if this does not occur on the first day of receiving tasks.
  - If you could not make it, here is a recorded [link](https://us02web.zoom.us/rec/share/3JMvcIj952BJboXuzB3OBLAmGK_daaa80CVP_fJcxUxsgT_ZLWk5A3LSnh9LzSSy) and the password is: 9N?T5@J7
  - Note: We do expect everyone to come to the live Welcome Webinar
